name: "Seplos MQTT RS485 Add-on"
description: "Read Seplos V2/V16 BMS data via RS485 and publish it to HA via MQTT"
version: "1.0.0-beta4"
slug: "seplos_mqtt_rs485_add-on"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
host_network: true
uart: true
usb: true
hassio_api: true
homeassistant_api: false
services:
  - mqtt:need
panel_icon: "mdi:battery"
options:
  rs485_remote_ip: ""
  rs485_remote_port: 4196
  serial_interface: "/tmp/vcom0"
  number_of_packs: 1
  min_cell_voltage: 2.5
  max_cell_voltage: 3.65
  mqtt_topic: "seplos"
  mqtt_update_interval: 1
  enable_ha_discovery: true
  ha_discovery_prefix: "homeassistant"
  invert_ha_dis_charge_measurements: false
  logging_level: "info"
schema:
  rs485_remote_ip: "str?"
  rs485_remote_port: "int?"
  serial_interface: "str"
  number_of_packs: "int(1,16)"
  min_cell_voltage: "float"
  max_cell_voltage: "float"
  mqtt_topic: "str"
  mqtt_update_interval: "int"
  enable_ha_discovery: "bool"
  ha_discovery_prefix: "str"
  invert_ha_dis_charge_measurements: "bool"
  logging_level: "list(info|error|debug)"
